ktor:
  application:
    modules:
      - dev.hoyeon.ApplicationKt.module
  deployment:
    port: 8883
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"